### ISSUE TITLE
Потерялись миллисекунды

### ISSUE THREAD

**Issue by DanaZL** [FearGateLP10/lesson3#1]
https://github.com/FearGateLP10/lesson3/blob/1a81aadc555a0424ba92dba33fcf2f69c0446bb4/date_time.py#L23

Сейчас ты отбрасываешь их, но можно решить задание и с ними

**Comment by FearGateLP10** [comment]
https://github.com/FearGateLP10/lesson3/commit/837c8ad308cc12f48d2f61ccf5bb837aef7d8957
